name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
-
  title: 'Features'
  labels:
  - 'enhancement'
  - 'feat'
  - 'feature'
-
  title: 'Bug Fixes'
  labels:
  - 'bug'
  - 'bugfix'
  - 'fix'
-
  title: 'Maintenance'
  labels:
  - 'chore'
  - 'style'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels: ['major']
  minor:
    labels: ['minor']
  patch:
    labels: ['patch']
  default: patch
exclude-labels: ['skip']
autolabeler:
-
  label: 'bug'
  branch:
  - '/bug\/.+/'
  - '/bugfix\/.+/'
  - '/fix\/.+/'
-
  label: 'enhancement'
  branch:
  - '/dependabot\/.+/'
  - '/enhancement\/.+/'
  - '/feat\/.+/'
  - '/feature\/.+/'
-
  label: 'chore'
  branch:
  - '/chore\/.+/'
  - '/style\/.+/'
template: |
  ## Release notes

  $CHANGES
